  export const pouchOptions = [
    { key: 'cushioned_premium', label: 'Cushioned Premium', price: 225 },
    { key: 'cushioned_normal', label: 'Cushioned Normal', price: 160 },
    { key: 'non_cushioned_big', label: 'NON-Cushioned Big', price: 110 },
    { key: 'non_cushioned_small', label: 'NON-Cushioned Small', price: 95 },
    { key: 'flat_pouch_normal', label: 'Flat pouch normal. material', price: 100 },
    { key: 'flat_pouch_quilted', label: 'Flat pouch quilted. material', price: 120 },
    { key: 'flat_pouch_premium', label: 'Flat pouch premium. material', price: 140 },
    { key: 'flat_pouch_premium_quilted', label: 'Flat pouch premium quilted ', price: 180 },
    { key: 'bottom_flat_pouch_normal', label: 'Bottom flat pouch normal material', price: 120 },
    { key: 'bottom_flat_pouch_quilted', label: 'Bottom flat pouch quilted material', price: 140 },
    { key: 'bottom_flat_pouch_premium', label: 'Bottom flat pouch premium material', price: 160 },
    { key: 'bottom_flat_pouch_premium_quilted', label: 'Bottom flat pouch premium quilted ', price: 200 },
    { key: 'box_pouch_normal', label: 'Box pouch normal', price: 180 },
    { key: 'box_pouch_quilted', label: 'Box pouch quilted', price: 200 },
    { key: 'box_pouch_premium', label: 'Box pouch premium', price: 260 },
    { key: 'box_pouch_premium_quilted', label: 'Box pouch premium quilted' , price: 299 },
  ];

  export const bagOptions = [
    { key: 'normal_tote', label: 'Normal tote', price: 195 },
    { key: 'lining_small', label: 'Lining small', price: 30 },
    { key: 'lining_big', label: 'Lining big', price: 60 },
    { key: 'pocket_inside', label: 'Pocket inside', price: 20 },
    { key: 'pocket_with_zipper_inside', label: 'Pocket w/ zipper inside', price: 45 },
    { key: 'small_pocket_outside', label: 'Small Pocket outside', price: 15 },
    { key: 'big_pocket_outside', label: 'Big Pocket outside', price: 30 },
    { key: 'pocket_with_zipper_outside', label: 'Pocket w/ zipper outside', price: 45 },
    { key: 'main_zipper_for_bag', label: 'Main zipper for bag', price: 30 },
    { key: 'extra_adjustable_strap', label: 'Extra adjustable strap', price: 50 },
    { key: 'extra_adjustable_strap_removable_small', label: 'Extra adjustable strap removable small', price: 80 },
    { key: 'extra_adjustable_strap_removable_big', label: 'Extra adjustable strap removable big', price: 100 },
    { key: 'magnetic_button', label: 'Magnetic button', price: 10 },
    { key: 'normal_button_on_main_part', label: 'Normal button on main part', price: 10 },
    { key: 'normal_button_on_pocket', label: 'Normal button on pocket', price: 10 },
    { key: 'embroidery_small_design', label: 'Embroidery small design', price: 50 },
    { key: 'embroidery_medium_design', label: 'Embroidery medium design', price: 130 },
    { key: 'embroidery_big_design', label: 'Embroidery big design', price: 250 },
    { key: 'name_embroidery_single_line', label: 'Name embroidery single line', price: 20 },
    { key: 'name_embroidery_thick', label: 'Name embroidery thick', price: 80 },
    { key: 'name_painting_small', label: 'Name painting small', price: 20 },
    { key: 'name_painting_big', label: 'Name painting big', price: 40 },
    { key: 'freehand_painting_simple', label: 'Freehand painting simple', price: 50 },
    { key: 'painting_medium', label: 'Painting medium', price: 150 },
    { key: 'painting_big', label: 'Painting big', price: 230 },
  ];
